const WORDS = [
    "apple", "beach", "brain", "bread", "brush", "chair", "chest", "chord", "click", "clock",
    "cloud", "dance", "diary", "drink", "earth", "flute", "fruit", "glass", "grape", "green",
    "ground", "heart", "house", "juice", "light", "lemon", "melon", "money", "music", "night",
    "ocean", "party", "piano", "pilot", "plane", "phone", "pizza", "plant", "radio", "river",
    "robot", "shirt", "shoes", "smile", "snake", "space", "spoon", "storm", "table", "tiger",
    "toast", "touch", "train", "truck", "voice", "water", "watch", "whale", "world", "write",
    "youth", "zebra", "arise", "slate", "adieu", "crane", "stare", "trace", "roate", "raise",
    "least", "learn", "point", "sound", "large", "small", "great", "black", "white", "brown",
    "quick", "slowly", "happy", "angry", "brave", "clear", "clean", "dirty", "early", "fresh",
    "heavy", "light", "lucky", "quiet", "rough", "sharp", "short", "sweet", "thick", "tough"
];

const VALID_GUESSES = [
    ...WORDS,
    "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again",
    "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone",
    "along", "alter", "among", "anger", "angle", "angry", "apart", "apple", "apply", "arena",
    "argue", "arise", "array", "aside", "asset", "audio", "audit", "avoid", "award", "aware",
    "awful", "awoke", "badly", "baker", "bases", "basic", "basis", "beach", "began", "begin",
    "begun", "being", "below", "bench", "billy", "birth", "black", "blade", "blank", "blast",
    "blend", "bless", "blind", "block", "blood", "board", "boast", "bonus", "boost", "bound",
    "brain", "brand", "bread", "break", "breed", "brief", "bring", "broad", "broke", "brown",
    "build", "built", "buyer", "cable", "calif", "carry", "catch", "cause", "chain", "chair",
    "chart", "chase", "cheap", "check", "chest", "chief", "child", "china", "chose", "civil",
    "claim", "class", "clean", "clear", "click", "clock", "close", "coach", "coast", "could",
    "count", "court", "cover", "craft", "crash", "cream", "crime", "cross", "crowd", "crown",
    "curve", "cycle", "daily", "dance", "dated", "dealt", "death", "debut", "delay", "depth",
    "doing", "doubt", "dozen", "draft", "drama", "drawn", "dream", "dress", "drill", "drink",
    "drive", "drove", "dying", "eager", "early", "earth", "eight", "elite", "empty", "enemy",
    "enjoy", "enter", "entry", "equal", "error", "event", "every", "exact", "exist", "extra",
    "faith", "false", "fault", "fiber", "field", "fifth", "fifty", "fight", "final", "first",
    "fixed", "flash", "fleet", "floor", "fluid", "focus", "force", "forth", "forty", "forum",
    "found", "frame", "frank", "fraud", "fresh", "front", "fruit", "fully", "funny", "giant",
    "given", "glass", "globe", "going", "grace", "grade", "grand", "grant", "grass", "great",
    "green", "gross", "group", "grown", "guard", "guess", "guest", "guide", "happy", "harry",
    "heart", "heavy", "hence", "night", "ocean", "order", "other", "ought", "paint", "paper",
    "party", "peace", "peter", "phase", "phone", "photo", "piece", "pilot", "pitch", "place",
    "plain", "plane", "plant", "plate", "point", "pound", "power", "press", "price", "pride",
    "prime", "print", "prior", "prize", "proof", "proud", "prove", "queen", "quick", "quiet",
    "quite", "radio", "raise", "range", "rapid", "ratio", "reach", "ready", "refer", "right",
    "rival", "river", "robin", "rough", "round", "route", "royal", "rural", "scale", "scene",
    "scope", "score", "sense", "serve", "seven", "setup", "shade", "shaft", "shake", "shall",
    "shape", "share", "sharp", "sheet", "shelf", "shell", "shift", "shirt", "shock", "shoot",
    "short", "shown", "sight", "since", "sixth", "sixty", "sized", "skill", "sleep", "slide",
    "small", "smart", "smile", "smith", "smoke", "solid", "solve", "sorry", "sound", "south",
    "space", "spare", "speak", "speed", "spend", "spent", "split", "spoke", "sport", "staff",
    "stage", "stake", "stand", "start", "state", "steam", "steel", "stick", "still", "stock",
    "stone", "stood", "store", "storm", "story", "strip", "stuck", "study", "stuff", "style",
    "sugar", "suite", "super", "sweet", "table", "taken", "taste", "taxes", "teach", "teeth",
    "terry", "texas", "thank", "theft", "their", "theme", "there", "these", "thick", "thing",
    "think", "third", "those", "three", "threw", "throw", "tight", "times", "tired", "title",
    "today", "topic", "total", "touch", "tough", "tower", "track", "trade", "train", "treat",
    "trend", "trial", "tried", "tries", "truck", "trust", "truth", "twice", "under", "undue",
    "union", "unity", "until", "upper", "upset", "urban", "usage", "usual", "valid", "value",
    "video", "virus", "visit", "vital", "voice", "waste", "watch", "water", "wheel", "where",
    "which", "while", "white", "whole", "whose", "woman", "women", "world", "worry", "worse",
    "worst", "worth", "would", "wound", "write", "wrong", "wrote", "yield", "young", "youth"
];
